name: 'deploy'

on: push

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: 'Build frontend'
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Setup node'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Cache NPM dependencies'
        uses: actions/cache@v1
        with:
          path: ./client/node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: 'Install packages'
        run: |
          cd client
          npm i

      - name: 'Build client'
        run: |
          cd client
          npm run build

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: client-bin
          path: ./client/build
          retention-days: 1

  build-backend:
    runs-on: ubuntu-latest
    name: 'Build backend'
    steps:
      - name: 'Install Go'
        uses: actions/setup-go@v2

      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Build server'
        run: make

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: server-bin
          path: ./server
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy'
    needs: [build-frontend, build-backend]
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2
